adaptive_threshold:
  initial_threshold: 0.0001
  min_motion_th: 0.0001
data:
  deskew: true
  max_range: 2.0
  min_range: 0.2
  preprocess: true
mapping:
  max_points_per_voxel: 30
out_dir: /mnt/data/fangqiang/TherHandsPro/subject_29_gesture_odom
